import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { readFile } from 'node:fs/promises'
import { origin, signup, workspace } from './helpers'
import { dateKey } from '../src/utils/dates'

test('career journey connects preparation, tasks, notes, company history, agenda, backup and sign-in', async ({ page }) => {
  const account = await signup(page, false), errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/saved')
  await page.getByRole('button', { name: 'Save job', exact: true }).first().click()
  let dialog = page.getByRole('dialog')
  await dialog.getByLabel('Company *').fill('Career Northstar')
  await dialog.getByLabel('Position *').fill('Platform Engineer')
  await dialog.getByLabel('Source').selectOption('Referral')
  await dialog.getByRole('button', { name: 'Save job', exact: true }).click()
  await page.getByRole('button', { name: 'Mark applied' }).click()
  await page.getByRole('button', { name: 'Create application', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Platform Engineer' })).toBeVisible()
  const app = (await workspace(page)).applications[0]
  await page.getByRole('link', { name: /Company profile:/ }).click()
  await page.getByRole('button', { name: 'Edit company' }).click()
  await page.getByLabel('Company research').fill('Ask about platform ownership')
  await page.getByRole('button', { name: 'Save company' }).click()
  await expect(page.getByText('Ask about platform ownership')).toBeVisible()
  await page.getByRole('link', { name: 'Platform Engineer' }).click()
  await page.getByRole('button', { name: 'Add contact', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Contact name *').fill('Career Recruiter')
  await dialog.getByRole('button', { name: 'Add contact', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('navigation', { name: 'Application workspace' }).getByRole('button', { name: 'Notes' }).click()
  await page.getByRole('button', { name: 'Add note', exact: true }).click()
  await page.getByLabel('Note *', { exact: true }).fill('Discussed career ownership and growth')
  await page.getByRole('button', { name: 'Save note' }).click()
  await expect(page.getByText('Discussed career ownership and growth')).toBeVisible()
  await page.getByRole('navigation', { name: 'Application workspace' }).getByRole('button', { name: 'Materials' }).click()
  await page.getByRole('button', { name: 'Edit materials' }).click()
  await page.getByLabel('Resume version', { exact: true }).fill('Platform v4')
  await page.getByLabel('Job description', { exact: true }).fill('Build reliable TypeScript services')
  await page.getByLabel('Skills & requirements').fill('TypeScript, SQL')
  await page.getByRole('button', { name: 'Save materials' }).click()
  await expect(page.getByText('Platform v4')).toBeVisible()
  await page.getByRole('navigation', { name: 'Application workspace' }).getByRole('button', { name: 'Overview' }).click()
  await page.getByRole('button', { name: 'Schedule', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Date & time *').fill(`${dateKey()}T15:00`)
  await dialog.getByLabel('Round', { exact: true }).fill('Platform round')
  await dialog.getByRole('button', { name: 'Schedule interview', exact: true }).click()
  await page.getByRole('button', { name: 'Prepare Platform round interview' }).click()
  dialog = page.getByRole('dialog', { name: 'Interview preparation' })
  await dialog.getByLabel('New preparation topic').fill('SQL joins')
  await dialog.getByRole('button', { name: 'Add topic' }).click()
  await dialog.getByLabel('SQL joins', { exact: true }).check()
  await dialog.getByLabel('Questions I want to ask').fill('How are service owners chosen?')
  await dialog.getByLabel('Questions I expect to receive').fill('Explain transaction isolation')
  await dialog.getByRole('button', { name: 'Save preparation' }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('button', { name: 'Set follow-up' }).click()
  await page.getByLabel('Follow up on').fill(dateKey())
  await page.getByRole('button', { name: 'Save follow-up' }).click()
  await page.getByRole('navigation', { name: 'Application workspace' }).getByRole('button', { name: 'Tasks' }).click()
  await page.getByRole('button', { name: 'Create task' }).click()
  await page.getByLabel('Task title *').fill('Career portfolio walkthrough')
  await page.getByLabel('Due date', { exact: true }).fill(dateKey())
  await page.getByRole('dialog').getByRole('button', { name: 'Create task', exact: true }).click()
  await expect(page.getByText('Career portfolio walkthrough', { exact: true })).toBeVisible()
  await page.goto('/today')
  await expect(page.locator('.agenda')).toContainText('Career portfolio walkthrough')
  await expect(page.locator('.agenda')).toContainText('Career Northstar')
  await page.getByRole('button', { name: 'Complete Career portfolio walkthrough' }).click()
  await expect(page.locator('.agenda')).not.toContainText('Career portfolio walkthrough')
  await page.goto('/calendar')
  await expect(page.locator('.selected-day')).toContainText('Career Northstar')
  await page.goto(`/applications/${app.id}`)
  await page.getByLabel('Application status', { exact: true }).selectOption('INTERVIEW')
  await expect(page.locator('.timeline')).toContainText('Career portfolio walkthrough')
  await expect(page.locator('.timeline')).toContainText('Interview preparation and reflection updated')
  await page.goto('/')
  await expect(page.locator('.overview-support-metrics')).toContainText('100% conversion')
  await page.goto('/analytics')
  await expect(page.getByText('1 of 1 reached an interview')).toBeVisible()
  await page.keyboard.press('Control+k')
  await page.getByLabel('Search commands').fill('career')
  dialog = page.getByRole('dialog', { name: 'Commands' })
  for (const group of ['Applications', 'Companies', 'Contacts', 'Tasks', 'Notes']) await expect(dialog.getByRole('heading', { name: group, exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.goto('/applications?source=Referral&status=INTERVIEW')
  await expect(page.getByRole('link', { name: 'Career Northstar', exact: true })).toBeVisible()
  await page.goto('/settings')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export JSON' }).click()
  const download = await downloadPromise, backup = JSON.parse(await readFile((await download.path())!, 'utf8'))
  expect(backup.version).toBe(4)
  expect(backup.career.tasks[0].status).toBe('COMPLETED')
  expect(backup.career.preparations[0].topics[0].done).toBe(true)
  await page.getByLabel('Import applications file').setInputFiles({ name: 'career.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(backup)) })
  await page.getByRole('button', { name: 'Replace & import' }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.getByLabel('Email address').fill(account.user.email)
  await page.getByLabel('Password', { exact: true }).fill('A thoughtful test passphrase')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible()
  const restored = await (await page.request.get('/api/workspace/export')).json()
  expect(restored.career.notes[0].body).toBe('Discussed career ownership and growth')
  expect(restored.career.materials[0].resumeVersion).toBe('Platform v4')
  expect(restored.career.preparations[0].questionsToAsk).toContain('service owners')
  const foreign = restored.applications[0]
  await page.context().clearCookies()
  await signup(page, false)
  for (const path of [`/applications/${foreign.id}`, `/companies/${foreign.companyId}`]) {
    await page.goto(path)
    await expect(page.getByText('Career Northstar', { exact: true })).not.toBeVisible()
  }
  for (const path of [`/applications/${foreign.id}`, `/companies/${foreign.companyId}`, `/tasks/${restored.career.tasks[0].id}`, `/applications/${foreign.id}/notes`, `/interviews/${foreign.interviews[0].id}/preparation`]) expect((await page.request.get('/api' + path)).status()).toBe(404)
  expect(errors).toEqual([])
})

for (const [width, theme] of [[320, 'light'], [375, 'light'], [768, 'light'], [1024, 'light'], [1440, 'light'], [375, 'dark'], [1440, 'dark']] as const) test(`CRM pages and dialogs are accessible and fit ${width}px in ${theme}`, async ({ page }, testInfo) => {
  test.setTimeout(150000)
  const data = await signup(page), app = data.applications.find(item => item.interviews.length)!
  await page.request.patch('/api/profile', { headers: { Origin: origin }, data: { ...data.profile, appearance: theme } })
  await page.setViewportSize({ width, height: 960 })
  await page.request.post('/api/tasks', { headers: { Origin: origin }, data: { title: 'Prepare portfolio', dueDate: dateKey(), applicationId: app.id } })
  const fit = async () => {
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const modal = page.getByRole('dialog')
    if (await modal.count()) expect(await modal.last().evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
    if ([375, 1440].includes(width)) expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()).violations).toEqual([])
  }
  for (const route of ['/today', '/calendar', '/tasks', '/companies', '/contacts', `/companies/${app.companyId}`, `/applications/${app.id}?tab=tasks`, `/applications/${app.id}?tab=materials`, `/applications/${app.id}?tab=notes`]) {
    await page.goto(route)
    await expect(page.locator('h1')).toBeVisible()
    await page.getByText('Loading…', { exact: true }).waitFor({ state: 'detached' })
    await fit()
    if (route === '/calendar' || route === '/today') await page.screenshot({ path: testInfo.outputPath(route.slice(1) + '.png'), fullPage: true })
  }
  for (const [route, button] of [['/tasks', 'Create task'], ['/companies', 'Add company'], [`/applications/${app.id}?tab=materials`, 'Edit materials'], [`/applications/${app.id}?tab=notes`, 'Add note'], [`/applications/${app.id}`, `Prepare ${app.interviews[0].round || app.interviews[0].type} interview`]]) {
    await page.goto(route)
    await page.getByRole('button', { name: button, exact: true }).first().click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await fit()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog')).not.toBeVisible()
  }
  await page.keyboard.press('Control+k')
  await page.getByLabel('Search commands').fill('Prepare')
  await expect(page.getByRole('button', { name: /Prepare portfolio/ })).toBeVisible()
  await page.keyboard.press('ArrowDown')
  await expect(page.locator('.command-results button').first()).toBeFocused()
  await fit()
})
