import { test, expect } from '@playwright/test'
import { signup } from './helpers'

test('account, application, board persistence, and session lifecycle', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const email = `flow-${Date.now()}@example.test`, password = 'A thoughtful test passphrase'
  await page.goto('/applications')
  await expect(page).toHaveURL(/\/login$/)
  await page.getByRole('link', { name: 'Create an account' }).click()
  await page.getByLabel('Full name').fill('Avery Morgan')
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Create your account' }).click()
  await expect(page).toHaveURL(/\/applications$/)
  await page.getByRole('button', { name: 'Add application', exact: true }).first().click()
  const dialog = page.getByRole('dialog', { name: 'Add application' })
  await dialog.getByRole('button', { name: 'Add application', exact: true }).click()
  await expect(dialog.getByText('Company is required')).toBeVisible()
  await dialog.getByLabel('Company *', { exact: true }).fill('Aurora Labs')
  await dialog.getByLabel('Position *', { exact: true }).fill('Frontend Engineer')
  await dialog.getByLabel('Work arrangement').selectOption('Remote')
  await dialog.getByRole('button', { name: 'Add application', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('link', { name: 'Aurora Labs', exact: true }).click()
  await page.getByRole('button', { name: 'Edit application', exact: true }).click()
  const edit = page.getByRole('dialog', { name: 'Edit application' })
  await edit.getByLabel('Position *', { exact: true }).fill('Senior Frontend Engineer')
  await edit.getByRole('button', { name: 'Save changes' }).click()
  await expect(edit).not.toBeVisible()
  await expect(page.getByRole('heading', { name: 'Senior Frontend Engineer' })).toBeVisible()
  await page.getByRole('link', { name: 'Kanban board' }).click()
  await page.getByLabel('Move Aurora Labs to status').selectOption('INTERVIEW')
  await expect(page.getByTestId('column-INTERVIEW').getByText('Aurora Labs')).toBeVisible()
  await page.reload()
  await expect(page.getByTestId('column-INTERVIEW').getByText('Aurora Labs')).toBeVisible()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByTestId('column-INTERVIEW').getByText('Aurora Labs')).toBeVisible()
  expect(errors).toEqual([])
})

test('invalid credentials and duplicate signup show recoverable errors without exposing another account', async ({ page }) => {
  const account = await signup(page)
  await page.context().clearCookies()
  await page.goto('/login')
  await page.getByLabel('Email address').fill(account.user.email)
  await page.getByLabel('Password', { exact: true }).fill('Incorrect passphrase')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Email or password is incorrect')
  await expect(page.locator('.sidebar')).not.toBeVisible()
  await page.getByRole('link', { name: 'Create an account' }).click()
  await page.getByLabel('Full name').fill('Someone Else')
  await page.getByLabel('Email address').fill(account.user.email)
  await page.getByLabel('Password', { exact: true }).fill('A different test passphrase')
  await page.getByRole('button', { name: 'Create your account' }).click()
  await expect(page.getByRole('alert')).toContainText('already exists')
  await page.getByLabel('Email address').fill(`separate-${crypto.randomUUID()}@example.test`)
  await page.getByRole('button', { name: 'Create your account' }).click()
  await expect(page.getByRole('heading', { name: 'No applications yet' })).toBeVisible()
  await expect(page.getByText('Linear', { exact: true })).not.toBeVisible()
})
