import { test, expect } from '@playwright/test'
import { addApplication, signup, workspace } from './helpers'

test('interview CRUD, upcoming conversations, follow-up completion and read reminders', async ({ page }) => {
  await signup(page, false)
  await page.goto('/applications')
  const app = await addApplication(page)
  await page.goto(`/applications/${app.id}`)
  await page.getByRole('button', { name: 'Schedule', exact: true }).click()
  let dialog = page.getByRole('dialog', { name: 'Schedule interview' })
  const date = new Date(Date.now() + 24 * 3600000)
  const local = new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16)
  await dialog.getByLabel('Date & time *').fill(local)
  await dialog.getByLabel('Interview type').selectOption('Technical')
  await dialog.getByLabel('Interviewer', { exact: true }).fill('Mina Chen')
  await dialog.getByLabel('Meeting URL').fill('https://meet.example.test/room')
  await dialog.getByLabel('Preparation & notes').fill('Discuss architecture and collaboration.')
  await dialog.getByRole('button', { name: 'Schedule interview' }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('heading', { name: 'Technical interview', exact: true })).toBeVisible()
  await page.goto('/')
  await expect(page.locator('.home-priorities .quest-list')).toContainText('Aurora Labs')
  await page.getByRole('button', { name: /Notifications/ }).click()
  dialog = page.getByRole('dialog', { name: 'Your reminders' })
  await expect(dialog).toContainText('Interview with Aurora Labs')
  await dialog.getByRole('button', { name: 'Mark all as read' }).click()
  await expect(dialog.getByRole('button', { name: 'Mark all as read' })).not.toBeVisible()
  expect((await workspace(page)).notifications[0].readAt).toBeTruthy()
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await page.goto(`/applications/${app.id}`)
  await page.getByRole('button', { name: 'Edit Technical interview' }).click()
  dialog = page.getByRole('dialog', { name: 'Edit interview' })
  await dialog.getByLabel('Outcome').selectOption('Next round')
  await dialog.getByRole('button', { name: 'Save interview' }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.locator('.interview-row')).toContainText('Next round')
  await page.getByRole('button', { name: 'Set follow-up' }).click()
  await page.getByLabel('Follow up on', { exact: true }).fill('2020-01-01')
  await page.getByRole('button', { name: 'Save follow-up' }).click()
  await expect(page.locator('.followup-panel')).toContainText('Overdue')
  expect((await workspace(page)).notifications[0].kind).toBe('followup')
  await page.getByRole('button', { name: /Notifications/ }).click()
  dialog = page.getByRole('dialog', { name: 'Your reminders' })
  await expect(dialog).toContainText('Jan 1, 2020')
  await expect(dialog).not.toContainText('12:00')
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Mark complete' }).click()
  await expect(page.locator('.followup-panel')).toContainText('Completed')
  expect((await workspace(page)).notifications).toHaveLength(0)
  await page.getByRole('button', { name: 'Delete Technical interview' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Delete interview', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Technical interview', exact: true })).not.toBeVisible()
  await expect(page.locator('.timeline')).toContainText('Follow-up completed')
  await expect(page.locator('.timeline')).toContainText('Interview removed')
})

test('contacts are reusable, editable, and unlinkable across applications', async ({ page }) => {
  await signup(page, false)
  await page.goto('/applications')
  const first = await addApplication(page, 'Aurora Labs')
  const second = await addApplication(page, 'Northstar')
  await page.goto(`/applications/${first.id}`)
  await page.getByRole('button', { name: 'Add contact', exact: true }).click()
  let dialog = page.getByRole('dialog', { name: 'Add a contact' })
  await dialog.getByLabel('Contact name *').fill('Nora Lane')
  await dialog.getByLabel('Contact email').fill('nora@example.test')
  await dialog.getByLabel('Role', { exact: true }).fill('Talent partner')
  await dialog.getByLabel('LinkedIn URL').fill('https://linkedin.com/in/nora')
  await dialog.getByLabel('Contact notes').fill('Met at a frontend meetup.')
  await dialog.getByRole('button', { name: 'Add contact', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.goto(`/applications/${second.id}`)
  await page.getByRole('button', { name: 'Add contact', exact: true }).click()
  dialog = page.getByRole('dialog', { name: 'Add a contact' })
  const contactId = (await workspace(page)).contacts[0].id
  await dialog.getByLabel('Use an existing contact').selectOption(contactId)
  await dialog.getByRole('button', { name: 'Add contact', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('button', { name: 'Edit Nora Lane' }).click()
  dialog = page.getByRole('dialog', { name: 'Edit contact' })
  await dialog.getByLabel('Contact name *').fill('Nora Chen')
  await dialog.getByRole('button', { name: 'Save contact' }).click()
  await expect(dialog).not.toBeVisible()
  const data = await workspace(page)
  expect(data.contacts).toHaveLength(1)
  expect(data.applications.every(app => app.contacts[0].name === 'Nora Chen')).toBe(true)
  await page.getByRole('button', { name: 'Unlink Nora Chen' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Unlink contact', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.locator('.contact-panel')).not.toContainText('Nora Chen')
  await page.goto(`/applications/${first.id}`)
  await expect(page.locator('.contact-panel')).toContainText('Nora Chen')
})
