import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { signup, workspace } from './helpers'

test('saved job becomes a complete application and remains recoverable after archiving', async ({ page }) => {
  await signup(page, false)
  await page.goto('/saved')
  await page.getByRole('button', { name: 'Save job', exact: true }).first().click()
  const dialog = page.getByRole('dialog', { name: 'Save a job' })
  await dialog.getByLabel('Company *').fill('Northstar')
  await dialog.getByLabel('Position *').fill('Platform Engineer')
  await dialog.getByLabel('Location').fill('Remote')
  await dialog.getByLabel('Job URL').fill('https://example.test/careers/platform')
  await dialog.getByLabel('Source').selectOption('Referral')
  await dialog.getByLabel('Notes').fill('Ask about the API team')
  await dialog.getByRole('button', { name: 'Save job', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Northstar' })).toBeVisible()
  await page.getByRole('button', { name: 'Mark applied' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Create application' }).click()
  await expect(page.getByRole('heading', { name: 'Platform Engineer' })).toBeVisible()
  await expect(page.locator('.details-facts')).toContainText('Referral')
  await expect(page.locator('.timeline')).toContainText('Applied to saved job')
  await page.getByRole('button', { name: 'Add contact' }).click()
  const contact = page.getByRole('dialog', { name: 'Add a contact' })
  await contact.getByLabel('Contact name *').fill('Morgan Lee')
  await contact.getByLabel('Contact email').fill('morgan@example.test')
  await contact.getByRole('button', { name: 'Add contact', exact: true }).click()
  await expect(page.locator('.contact-panel')).toContainText('Morgan Lee')
  await page.getByRole('button', { name: 'Set follow-up' }).click()
  await page.getByLabel('Follow up on').fill('2020-01-01')
  await page.getByLabel('Reason', { exact: true }).fill('Check application status')
  await page.getByLabel('Follow-up note').fill('Write to Morgan')
  await page.getByRole('button', { name: 'Save follow-up' }).click()
  await expect(page.locator('.next-step-panel')).toContainText('Check application status')
  await page.getByRole('button', { name: 'Schedule', exact: true }).click()
  const interview = page.getByRole('dialog', { name: 'Schedule interview' })
  const date = new Date(Date.now() + 2 * 86400000)
  await interview.getByLabel('Date & time *').fill(new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16))
  await interview.getByLabel('Interview type').selectOption('Technical')
  await interview.getByLabel('Round').fill('Round 1')
  await interview.getByLabel('Location').fill('Video call')
  await interview.getByRole('button', { name: 'Schedule interview' }).click()
  await expect(page.locator('.interview-row')).toContainText('Round 1')
  const id = (await workspace(page)).applications[0].id
  await page.goto('/kanban')
  await page.getByLabel('Move Northstar to status').selectOption('INTERVIEW')
  await page.goto('/analytics')
  await expect(page.getByText('1 of 1 reached an interview')).toBeVisible()
  await expect(page.locator('.source-breakdown')).toContainText('Referral')
  await page.goto('/applications?source=Referral')
  await expect(page.getByRole('link', { name: 'Northstar', exact: true })).toBeVisible()
  await page.getByRole('checkbox', { name: 'Select Northstar Platform Engineer' }).check()
  await page.getByLabel('Bulk action').selectOption('archive')
  await page.getByRole('button', { name: 'Apply', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Northstar', exact: true })).not.toBeVisible()
  await page.getByRole('button', { name: /^Archive/ }).click()
  await expect(page.getByRole('link', { name: 'Northstar', exact: true })).toBeVisible()
  await page.goto(`/applications/${id}`)
  await page.getByRole('button', { name: 'Restore' }).click()
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('dialog', { name: 'Commands' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Search commands' }).fill('analytics')
  await page.getByRole('button', { name: 'Open analytics' }).click()
  await expect(page).toHaveURL(/\/analytics$/)
  await page.goto('/settings')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export JSON' }).click()
  const download = await downloadPromise
  const backup = JSON.parse(await readFile((await download.path())!, 'utf8')) as { version: number; savedJobs: unknown[]; applications: { company: string }[] }
  expect(backup.version).toBe(3)
  expect(backup.savedJobs).toHaveLength(0)
  expect(backup.applications[0].company).toBe('Northstar')
  await page.reload()
  expect((await workspace(page)).applications[0]).toMatchObject({ source: 'Referral', followUpReason: 'Check application status', archivedAt: '' })
})
