import { test, expect } from '@playwright/test'
import { addApplication, workspace } from './helpers'
import { dateKey } from '../src/utils/dates'
import type { Journey } from '../src/domain/journey'

test('real actions persist XP, achievements, quests and companion through refresh and sign-in', async ({ page }) => {
  const email = `journey-${crypto.randomUUID()}@example.test`, password = 'A thoughtful test passphrase'
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  const progress = async () => await (await page.request.get('/api/journey')).json() as Journey
  await page.goto('/signup')
  await page.getByLabel('Full name').fill('Robin Walker')
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Create your account' }).click()
  await expect(page.getByRole('heading', { name: /Good .*Robin/ })).toBeVisible()
  const app = await addApplication(page, 'Journey Northstar')
  await expect.poll(async () => (await progress()).xp).toBe(30)
  await expect(page.locator('.home-journey')).toHaveAttribute('aria-label', /30 XP/)
  await page.goto('/journey')
  await expect(page.locator('.journey-level')).toContainText('30 XP')
  await expect(page.getByRole('img', { name: 'Fox companion, evolution 1' })).toBeVisible()
  await expect(page.locator('.achievement.earned')).toContainText('First step')
  await page.getByRole('button', { name: 'Cat', exact: true }).click()
  await expect(page.getByRole('img', { name: 'Cat companion, evolution 1' })).toBeVisible()
  await page.goto('/tasks')
  await page.getByRole('button', { name: 'Create task', exact: true }).click()
  await page.getByLabel('Task title *').fill('Polish portfolio story')
  await page.getByLabel('Due date', { exact: true }).fill(dateKey())
  await page.getByRole('dialog').getByRole('button', { name: 'Create task', exact: true }).click()
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await page.goto('/journey')
  await expect(page.locator('.quest-list')).toContainText('Polish portfolio story')
  await page.goto('/tasks')
  await page.getByRole('button', { name: 'Complete Polish portfolio story' }).click()
  await expect.poll(async () => (await progress()).xp).toBe(45)
  await page.goto('/journey')
  await expect(page.locator('.quest-complete')).toContainText('A task completed')
  await page.goto(`/applications/${app.id}`)
  await page.getByRole('button', { name: 'Schedule', exact: true }).click()
  await page.getByLabel('Date & time *').fill(`${dateKey()}T15:00`)
  await page.getByLabel('Round', { exact: true }).fill('Portfolio conversation')
  await page.getByRole('button', { name: 'Schedule interview', exact: true }).click()
  await expect.poll(async () => (await progress()).xp).toBe(70)
  await page.getByRole('button', { name: 'Edit Video interview', exact: true }).click()
  await page.getByLabel('Outcome', { exact: true }).selectOption('Completed')
  await page.getByRole('button', { name: 'Save interview', exact: true }).click()
  await expect.poll(async () => (await progress()).xp).toBe(130)
  await page.goto('/journey')
  await expect(page.locator('.journey-level')).toContainText('130 XP')
  await expect(page.locator('.journey-level > strong')).toHaveText('02')
  await expect(page.locator('.achievement.earned').filter({ hasText: 'You showed up' })).toBeVisible()
  const before = await progress()
  await page.reload()
  await expect(page.locator('.journey-level')).toContainText('130 XP')
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('.journey-level')).toContainText('130 XP')
  expect(await progress()).toEqual(before)
  expect((await workspace(page)).applications).toHaveLength(1)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('navigation', { name: 'Quick navigation' }).getByRole('link', { name: 'Journey' }).click()
  await expect(page.getByRole('img', { name: 'Cat companion, evolution 1' })).toBeVisible()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  expect(await page.locator('.companion-art').evaluate(el => Number.parseFloat(getComputedStyle(el).animationDuration))).toBeLessThanOrEqual(.01)
  await page.getByRole('switch', { name: 'Show journey progress and celebrations in my workspace' }).click()
  await expect(page.getByRole('switch', { name: 'Show journey progress and celebrations in my workspace' })).toHaveAttribute('aria-checked', 'false')
  await page.getByRole('navigation', { name: 'Quick navigation' }).getByRole('link', { name: 'Home' }).click()
  await expect(page.locator('.home-journey')).toHaveCount(0)
  expect(errors).toEqual([])
})
