import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { signup, workspace } from './helpers'
test.beforeEach(async ({ page }) => { await signup(page) })

const storageKey = 'waypoint.workspace.v1'
async function applications(page: Page) {
  return (await workspace(page)).applications
}
async function addApplication(page: Page, company: string) {
  await page.getByRole('button', { name: 'Add application', exact: true }).first().click()
  const dialog = page.getByRole('dialog', { name: 'Add application' })
  await dialog.getByLabel('Company *', { exact: true }).fill(company)
  await dialog.getByLabel('Position *', { exact: true }).fill('Frontend Engineer')
  await dialog.getByLabel('Location', { exact: true }).fill('Astana')
  await dialog.getByLabel('Annual salary (USD)', { exact: true }).fill('90000')
  await dialog.getByRole('button', { name: 'Add application', exact: true }).click()
  await expect(dialog).not.toBeVisible()
}

test('create, validate, edit, move, view analytics, reload, and delete an application', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Add application', exact: true }).click()
  let dialog = page.getByRole('dialog', { name: 'Add application' })
  await dialog.getByRole('button', { name: 'Add application', exact: true }).click()
  await expect(dialog.getByText('Company is required')).toBeVisible()
  await expect(dialog.getByText('Position is required')).toBeVisible()
  await dialog.getByLabel('Company *', { exact: true }).fill('Aurora Labs')
  await dialog.getByLabel('Position *', { exact: true }).fill('Frontend Engineer')
  await dialog.getByLabel('Location', { exact: true }).fill('Astana')
  await dialog.getByLabel('Annual salary (USD)', { exact: true }).fill('-100')
  await dialog.getByLabel('Job URL', { exact: true }).fill('javascript:alert(1)')
  await dialog.getByText('People, interviews & notes', { exact: true }).click()
  await dialog.getByLabel('Recruiter email', { exact: true }).fill('wrong')
  await dialog.getByRole('button', { name: 'Add application', exact: true }).click()
  await expect(dialog.getByText(/Enter a positive annual salary/)).toBeVisible()
  await expect(dialog.getByText('Enter a complete http:// or https:// URL')).toBeVisible()
  await expect(dialog.getByText('Enter a valid email address')).toBeVisible()
  await dialog.getByLabel('Annual salary (USD)', { exact: true }).fill('90000')
  await dialog.getByLabel('Job URL', { exact: true }).fill('https://example.com/jobs/frontend')
  await dialog.getByLabel('Recruiter email', { exact: true }).fill('jamie@example.com')
  await dialog.getByLabel('Recruiter', { exact: true }).fill('Jamie Lee')
  await dialog.getByLabel('Tags', { exact: true }).fill('React, Portfolio')
  await dialog.getByLabel('Notes', { exact: true }).fill('Ask about the design system and engineering ownership.')
  await dialog.getByRole('button', { name: 'Add application', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.locator('.activity-feed')).toContainText('Aurora Labs')
  await page.reload()
  await page.locator('.activity-feed a').filter({ hasText: 'Aurora Labs' }).first().click()
  await expect(page.getByRole('heading', { name: 'Frontend Engineer', exact: true })).toBeVisible()
  await expect(page.getByText('Jamie Lee', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Edit application', exact: true }).click()
  dialog = page.getByRole('dialog', { name: 'Edit application', exact: true })
  await dialog.getByLabel('Position *', { exact: true }).fill('Staff Frontend Engineer')
  await dialog.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Staff Frontend Engineer', exact: true })).toBeVisible()
  await page.goto('/kanban')
  await page.getByLabel('Move Aurora Labs to status', { exact: true }).selectOption('INTERVIEW')
  await page.reload()
  await expect(page.getByTestId('column-INTERVIEW').getByText('Aurora Labs', { exact: true })).toBeVisible()
  await page.goto('/analytics')
  await expect(page.getByText('6 of 25 reached an interview')).toBeVisible()
  const app = (await applications(page)).find(item => item.company === 'Aurora Labs')!
  await page.goto(`/applications/${app.id}`)
  await page.getByRole('button', { name: 'Delete application', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Staff Frontend Engineer' })).toBeVisible()
  await page.getByRole('button', { name: 'Delete application', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Delete application', exact: true }).click()
  await page.reload()
  expect((await applications(page)).find(item => item.company === 'Aurora Labs')).toBeUndefined()
  expect(errors).toEqual([])
})

test('search, compose filters, clear filters, sort, and paginate', async ({ page }) => {
  await page.goto('/applications')
  await expect(page.getByRole('button', { name: 'Add application', exact: true })).toHaveCount(1)
  const search = page.getByRole('textbox', { name: 'Search applications' })
  await search.fill('Jamie Chen')
  await expect(page.locator('.opportunity-row')).toHaveCount(1)
  await expect(page.getByRole('link', { name: 'Linear', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Clear search', exact: true }).click()
  await expect(page.locator('.opportunity-row')).toHaveCount(10)
  await page.getByRole('button', { name: /^Interview\s*3$/ }).click()
  await page.getByRole('button', { name: 'Filters', exact: true }).click()
  await page.getByLabel('Location', { exact: true }).selectOption('Astana')
  await page.getByLabel('Employment type', { exact: true }).selectOption('Full-time')
  await page.getByLabel('Min salary (USD)', { exact: true }).fill('60000')
  await page.getByLabel('Max salary (USD)', { exact: true }).fill('70000')
  const date = (await applications(page)).find(app => app.company === 'Kaspi.kz')!.dateApplied
  await page.getByLabel('Applied from', { exact: true }).fill(date)
  await page.getByLabel('Applied through', { exact: true }).fill(date)
  await expect(page.locator('.opportunity-row')).toHaveCount(1)
  await expect(page.getByRole('link', { name: 'Kaspi.kz', exact: true })).toBeVisible()
  const filterToggle = page.getByRole('button', { name: /^Filters/ })
  await filterToggle.click()
  await expect(filterToggle).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByLabel('Location', { exact: true })).not.toBeVisible()
  await expect(page.locator('.opportunity-row')).toHaveCount(1)
  await page.reload()
  await expect(page.locator('.opportunity-row')).toHaveCount(1)
  await page.getByRole('button', { name: 'Clear all filters', exact: true }).click()
  await page.getByLabel('Sort applications', { exact: true }).selectOption('company')
  await expect(page.locator('.opportunity-row').first()).toContainText('Air Astana')
  await page.getByLabel('Sort applications', { exact: true }).selectOption('salary')
  await expect(page.locator('.opportunity-row').first()).toContainText('Figma')
  await page.getByRole('button', { name: 'Next page', exact: true }).click()
  await expect(page.getByText('Page 2 of 3', { exact: true })).toBeVisible()
  await search.fill('does-not-exist')
  await expect(page.getByRole('heading', { name: 'A different direction?' })).toBeVisible()
  await page.getByRole('button', { name: 'Clear search', exact: true }).click()
  await expect(page.locator('.opportunity-row')).toHaveCount(10)
})

test('pointer drag and drop updates the board, dashboard, and storage', async ({ page }) => {
  await page.goto('/kanban')
  const id = (await applications(page)).find(app => app.company === 'Vercel')!.id
  const source = page.getByTestId(`card-${id}`).getByRole('button', { name: /Drag Vercel application/ })
  const target = page.getByTestId('column-SCREENING')
  const start = await source.boundingBox()
  const end = await target.boundingBox()
  expect(start).not.toBeNull()
  expect(end).not.toBeNull()
  await page.mouse.move(start!.x + start!.width / 2, start!.y + start!.height / 2)
  await page.mouse.down()
  await page.mouse.move(start!.x + 10, start!.y + 12, { steps: 5 })
  await page.mouse.move(end!.x + end!.width / 2, end!.y + 70, { steps: 20 })
  await expect(target).toHaveClass(/is-over/)
  await page.mouse.up()
  await expect(target.getByTestId(`card-${id}`)).toBeVisible()
  await page.reload()
  await expect(page.getByTestId('column-SCREENING').getByTestId(`card-${id}`)).toBeVisible()
  await page.goto('/')
  await expect(page.locator('.route-stations a').filter({ hasText: 'In conversation' }).locator('strong')).toHaveText('8')
})

test('export, invalid import, valid import, reset and clear confirmation', async ({ page }) => {
  await page.goto('/settings')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export JSON', exact: true }).click()
  const download = await downloadPromise
  const file = await download.path()
  const original = JSON.parse(await readFile(file!, 'utf8')) as { version: number; applications: { company: string }[]; career?: unknown }
  expect(original.version).toBe(4)
  expect(original.applications).toHaveLength(24)
  await page.getByLabel('Import applications file').setInputFiles({ name: 'broken.json', mimeType: 'application/json', buffer: Buffer.from('{broken') })
  await expect(page.getByRole('alert')).toContainText('Your existing data is unchanged')
  expect(await applications(page)).toHaveLength(24)
  // Exercise legacy import compatibility independently of v4 relationship restoration.
  original.version = 3
  delete original.career
  original.applications[0].company = 'Restored Company'
  await page.getByLabel('Import applications file').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(original)) })
  await expect(page.getByRole('dialog', { name: 'Replace your workspace?' })).toBeVisible()
  await page.getByRole('button', { name: 'Replace & import', exact: true }).click()
  await page.reload()
  expect((await applications(page))[0].company).toBe('Restored Company')
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click()
  await page.getByRole('button', { name: 'Reset demo data', exact: true }).click()
  expect((await applications(page)).some(app => app.company === 'Linear')).toBe(true)
  await page.getByRole('button', { name: 'Clear data', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(await applications(page)).toHaveLength(24)
  await page.getByRole('button', { name: 'Clear data', exact: true }).click()
  await page.getByRole('button', { name: 'Clear all applications', exact: true }).click()
  await page.reload()
  expect(await applications(page)).toHaveLength(0)
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Find your starting point' })).toBeVisible()
  await page.goto('/analytics')
  await expect(page.getByText('0 of 0 reached an interview')).toBeVisible()
  await page.goto('/kanban')
  await expect(page.locator('.kanban-card')).toHaveCount(0)
})

test('profile, theme and notification settings persist', async ({ page }) => {
  await page.goto('/settings')
  await page.getByLabel('Full name', { exact: true }).fill('Taylor Brooks')
  await page.getByRole('spinbutton', { name: 'Weekly application goal', exact: true }).fill('12')
  await page.getByRole('button', { name: 'Dark', exact: true }).click()
  await page.getByRole('switch', { name: 'Interview reminders' }).click()
  await page.getByRole('button', { name: 'Save profile', exact: true }).click()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.getByLabel('Full name')).toHaveValue('Taylor Brooks')
  await expect(page.getByRole('spinbutton', { name: 'Weekly application goal', exact: true })).toHaveValue('12')
  await expect(page.getByRole('switch', { name: 'Interview reminders' })).toHaveAttribute('aria-checked', 'false')
  await page.getByRole('button', { name: /Notifications/ }).click()
  await expect(page.getByRole('dialog')).not.toContainText('Interview with')
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByRole('button', { name: 'System', exact: true }).click()
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /Good .*Taylor/ })).toBeVisible()
})

test('malformed localStorage fails gracefully and can be recovered', async ({ page }) => {
  await page.addInitScript(key => { if (!sessionStorage.getItem('corruption-set')) { localStorage.setItem(key, '{broken'); sessionStorage.setItem('corruption-set', 'true') } }, storageKey)
  await page.goto('/')
  await expect(page.getByRole('alert')).toHaveCount(0)
  expect(await page.evaluate(key => localStorage.getItem(key), storageKey)).toBe('{broken')
  await page.goto('/settings')
  await page.getByRole('button', { name: 'Import browser data' }).click()
  await expect(page.getByRole('alert')).toContainText('browser backup could not be read')
  await page.getByRole('button', { name: 'Reset demo', exact: true }).click()
  await page.getByRole('button', { name: 'Reset demo data', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('alert')).toHaveCount(0)
  expect(await applications(page)).toHaveLength(24)
})

test('mobile navigation, form, details and keyboard status changes work', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('dialog').getByRole('link', { name: /Applications/ }).click()
  await expect(page.getByRole('heading', { name: 'Applications' })).toBeVisible()
  await addApplication(page, 'Mobile Opportunity')
  await page.getByRole('link', { name: 'Mobile Opportunity', exact: true }).click()
  const status = page.getByLabel('Application status', { exact: true })
  await status.focus()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(status).toHaveValue('SCREENING')
  await page.reload()
  await expect(page.getByLabel('Application status', { exact: true })).toHaveValue('SCREENING')
  const app = (await applications(page)).find(item => item.company === 'Mobile Opportunity')!
  expect(app.status).toBe('SCREENING')
})

test('unsaved forms confirm discard and dialogs retain keyboard focus', async ({ page }) => {
  await page.goto('/')
  const opener = page.getByRole('button', { name: 'Add application', exact: true })
  await opener.click()
  const dialog = page.getByRole('dialog', { name: 'Add application' })
  await dialog.getByLabel('Company *', { exact: true }).fill('Unsaved Co')
  await page.keyboard.press('Escape')
  const confirm = page.getByRole('dialog', { name: 'Discard your changes?' })
  await expect(confirm).toBeVisible()
  await confirm.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await confirm.getByRole('button', { name: 'Discard changes', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(opener).toBeFocused()
  expect(await applications(page)).toHaveLength(24)
})

test('unknown routes and missing applications offer recovery', async ({ page }) => {
  await page.goto('/missing-page')
  await expect(page.getByRole('link', { name: 'Back to overview' })).toBeVisible()
  await page.goto('/applications/no-such-id')
  await expect(page.getByRole('link', { name: 'Back to applications' })).toBeVisible()
})
