import { Link } from 'react-router-dom'
import { Check, Flag, Footprints, ArrowUpRight } from 'lucide-react'
import { useJourney } from '../hooks/useJourney'
import { useMutation } from '../hooks/useResource'
import { ACHIEVEMENTS, COMPANIONS } from '../domain/journey'
import { Companion } from '../components/Companion'
import { QuestList } from '../components/JourneyProgress'
import { RemoteState } from '../components/ui/RemoteState'

export default function Journey() {
  const query = useJourney(), mutation = useMutation()
  if (!query.data) return <><h1>Journey</h1><RemoteState {...query} /></>
  const data = query.data, unlocked = new Set(data.achievements.map(item => item.id))
  return <div className="journey-page"><header className="journey-heading"><p className="eyebrow">Every step stays with you</p><h1>Your journey.</h1><p>A record of the work you put in. At your own pace.</p></header>
    <section className="journey-landscape" aria-label="Career progress"><div className="journey-level"><span className="eyebrow">Career level</span><strong>{String(data.progress.level).padStart(2, '0')}</strong><h2>{data.progress.title}</h2><progress aria-label="Career level progress" value={data.progress.current} max={data.progress.required} /><p><b>{data.xp.toLocaleString()} XP</b><span>{data.progress.next - data.xp} to level {data.progress.level + 1}</span></p></div><div className="companion-place"><svg className="landscape-route" viewBox="0 0 600 240" aria-hidden="true"><path d="M-20 210C100 210 45 100 170 130S260 245 380 160S450 80 625 90" /><circle cx="380" cy="160" r="6" /><circle cx="170" cy="130" r="5" /></svg><Companion xp={data.xp} kind={data.companion} stage={data.progress.stage} celebrating={data.events[0]?.source === 'action'} /><div className="companion-caption"><span className="eyebrow">Your travelling companion</span><strong>{data.companion === 'fox' ? 'Ember' : data.companion === 'cat' ? 'Pip' : 'Clover'}</strong><small>{data.progress.stage === 1 ? 'A curious beginning' : data.progress.stage === 2 ? 'A scarf for the road' : data.progress.stage === 3 ? 'A compass for new horizons' : 'Ready for any trail'}</small></div></div></section>
    <div className="journey-choices"><fieldset disabled={mutation.pending}><legend>Choose your companion</legend>{COMPANIONS.map(kind => <button key={kind} aria-pressed={data.companion === kind} onClick={() => void mutation.save('/journey/preferences', 'PATCH', { companion: kind })}>{kind === 'hare' ? 'Hare' : kind === 'cat' ? 'Cat' : 'Fox'}{data.companion === kind && <Check size={14} />}</button>)}</fieldset><p>Grows with you at levels 5, 10 &amp; 20.</p></div>{mutation.error && <p role="alert" className="form-error">{mutation.error}</p>}
    <div className="journey-work"><section><div className="section-heading"><div><p className="eyebrow">Optional, always</p><h2>Today’s small steps</h2></div><Footprints size={22} /></div>{data.quests.length ? <QuestList steps={data.quests} /> : <div className="quiet-empty"><p>A clear path today. Choose something that matters to you.</p><Link to="/tasks" className="text-link">Plan a next step <ArrowUpRight size={15} /></Link></div>}</section><aside className="weekly-intention"><p className="eyebrow">This week’s intention</p><h2>{data.weekly.complete ? 'You made room for progress.' : 'A little, consistently.'}</h2><strong>{data.weekly.count}<span> / {data.weekly.target}</span></strong><p>Distinct applications submitted this week.</p><progress aria-label="Journey weekly goal" value={Math.min(data.weekly.count, data.weekly.target)} max={data.weekly.target} /><Link to="/settings" className="text-link">Adjust your pace <ArrowUpRight size={14} /></Link><div className="activity-rhythm"><b>{data.streak.activeDays} active {data.streak.activeDays === 1 ? 'day' : 'days'}</b><p>{data.streak.current > 1 ? `${data.streak.current} days of meaningful steps in a row.` : 'Days off belong in the journey, too.'}</p></div></aside></div>
    <section className="milestone-section"><div className="section-heading"><div><p className="eyebrow">Waypoints ahead</p><h2>Build on what you’ve done.</h2></div><Flag size={22} /></div><ol className="milestone-route">{[{ label: '10 applications', count: data.counts.APPLICATION_SUBMITTED ?? 0, target: 10 }, { label: '5 connections', count: data.counts.CONTACT_ADDED ?? 0, target: 5 }, { label: '10 interviews completed', count: data.counts.INTERVIEW_COMPLETED ?? 0, target: 10 }].map(item => <li key={item.label}><span className={item.count >= item.target ? 'milestone-dot reached' : 'milestone-dot'}>{item.count >= item.target ? <Check size={14} /> : <span />}</span><strong>{item.label}</strong><small>{Math.min(item.count, item.target)} of {item.target}{item.count >= item.target ? ' · Reached' : ''}</small></li>)}</ol></section>
    <section className="achievement-section"><div className="section-heading"><div><p className="eyebrow">Earned along the way</p><h2>Moments worth keeping.</h2></div><span className="muted">{unlocked.size} / {ACHIEVEMENTS.length}</span></div><div className="achievement-ledger">{ACHIEVEMENTS.map((item, index) => <article key={item.id} className={unlocked.has(item.id) ? 'achievement earned' : 'achievement'}><span className="achievement-seal">{unlocked.has(item.id) ? <Check size={19} /> : String(index + 1).padStart(2, '0')}</span><div><h3>{item.title}</h3><p>{item.description}</p><small>{unlocked.has(item.id) ? 'Earned' : `${Math.min(data.counts[item.type] ?? 0, item.target)} / ${item.target}`}</small></div></article>)}</div></section>
    <details className="journey-explainer"><summary>How progress works</summary><p>XP records meaningful actions once: applications 30, contacts 10, scheduling an interview 25, preparing 40, completing an interview 60, follow-ups 25 and tasks 15. Daily limits keep progress balanced. Repeated edits, imports and demo data earn no XP. Completed steps already include their action reward; quests do not add a second reward. Weeks and active days use UTC.</p><p>Earlier work may be credited as a one-time backfill. It never counts as activity today. Weekly intentions are personal guides, with no bonus or penalty.</p><ol>{data.events.map(event => <li key={event.id}>{event.type.toLowerCase().replaceAll('_', ' ')} <b>+{event.xp} XP</b>{event.source === 'backfill' && ' · Earlier work'}</li>)}</ol></details>
    <div className="journey-opt-out"><button type="button" className={`switch ${data.enabled ? 'on' : ''}`} role="switch" aria-checked={data.enabled} aria-label="Show journey progress and celebrations in my workspace" disabled={mutation.pending} onClick={() => void mutation.save('/journey/preferences', 'PATCH', { enabled: !data.enabled })}><span /></button><span>Show journey progress and celebrations in my workspace</span></div>
  </div>
}
